services:
  - type: web
    name: agri-backend
    env: node
    plan: free
    rootDir: agri-blockchain-backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: agri-payments-backend
    env: node
    plan: free
    rootDir: blockchain-payment-backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
